package com.jdzu.familyfood.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class DatabaseExportService {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private final ObjectMapper objectMapper = new ObjectMapper();

    @PostConstruct
    public void exportDatabase() {
        // 确保在后台线程执行，避免影响启动
        new Thread(() -> {
            try {
                Thread.sleep(5000); // 增加等待时间，确保数据库连接完全就绪
                
                // 检查数据源是否可用
                if (jdbcTemplate.getDataSource() == null) {
                    System.err.println("❌ 数据源未初始化，跳过数据库导出");
                    return;
                }
                
                // 尝试获取一个连接来验证连接池状态
                try {
                    jdbcTemplate.queryForObject("SELECT 1", Integer.class);
                } catch (Exception e) {
                    System.err.println("❌ 数据库连接不可用，跳过数据库导出: " + e.getMessage());
                    return;
                }
                
                doExport();
            } catch (InterruptedException e) {
                System.err.println("❌ 数据库导出线程被中断");
                Thread.currentThread().interrupt();
            } catch (Exception e) {
                System.err.println("❌ 数据库导出失败: " + e.getMessage());
                e.printStackTrace();
            }
        }).start();
    }

    private void doExport() {
        try {
            // 再次检查连接池状态
            try {
                jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            } catch (Exception e) {
                System.err.println("❌ 数据库连接不可用，取消导出: " + e.getMessage());
                return;
            }
            
            // 配置 JSON 格式化
            objectMapper.registerModule(new JavaTimeModule());
            objectMapper.enable(SerializationFeature.INDENT_OUTPUT);

            // 准备导出数据
            Map<String, Object> exportData = new LinkedHashMap<>();
            exportData.put("databaseName", getDatabaseName());
            exportData.put("exportTime", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));

            // 获取所有表
            List<String> tables = jdbcTemplate.queryForList("SHOW TABLES", String.class);

            Map<String, List<Map<String, Object>>> tablesData = new LinkedHashMap<>();
            for (String table : tables) {
                List<Map<String, Object>> rows = jdbcTemplate.queryForList("SELECT * FROM `" + table + "`");
                tablesData.put(table, rows);
            }

            exportData.put("tables", tablesData);

            File dumpDir = new File("./database-dump");
            if (!dumpDir.exists()) {
                dumpDir.mkdirs();
            }

            String jsonFilename = "./database-dump/database.json";
            objectMapper.writeValue(new File(jsonFilename), exportData);

            String sqlFilename = "./database-dump/database.sql";
            writeSqlDump(sqlFilename, tables);

            System.out.println("✅ 数据库已导出: " + jsonFilename);
            System.out.println("✅ SQL 已导出: " + sqlFilename);
            System.out.println("   数据库名: " + getDatabaseName());
            System.out.println("   共导出 " + tables.size() + " 张表, " + getTotalRecords(tablesData) + " 条记录");

        } catch (Exception e) {
            System.err.println("❌ 数据库导出失败: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void writeSqlDump(String filename, List<String> tables) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename, false))) {
            writer.write("-- Database dump generated by DatabaseExportService");
            writer.newLine();
            writer.write("-- Generated at " + LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
            writer.newLine();
            writer.write("SET FOREIGN_KEY_CHECKS = 0;");
            writer.newLine();
            writer.newLine();

            for (String table : tables) {
                writer.write("-- ----------------------------");
                writer.newLine();
                writer.write("-- Table structure for `" + table + "`");
                writer.newLine();
                writer.write("-- ----------------------------");
                writer.newLine();

                String createTableSql = jdbcTemplate.queryForObject(
                        "SHOW CREATE TABLE `" + table + "`",
                        (rs, rowNum) -> rs.getString(2)
                );
                writer.write(createTableSql);
                writer.write(";");
                writer.newLine();
                writer.newLine();

                List<Map<String, Object>> rows = jdbcTemplate.queryForList("SELECT * FROM `" + table + "`");
                if (!rows.isEmpty()) {
                    writer.write("LOCK TABLES `" + table + "` WRITE;");
                    writer.newLine();
                    for (Map<String, Object> row : rows) {
                        writer.write(buildInsertSql(table, row));
                        writer.write(";");
                        writer.newLine();
                    }
                    writer.write("UNLOCK TABLES;");
                    writer.newLine();
                    writer.newLine();
                }
            }

            writer.write("SET FOREIGN_KEY_CHECKS = 1;");
            writer.newLine();
        }
    }

    private String buildInsertSql(String table, Map<String, Object> row) {
        StringBuilder columns = new StringBuilder();
        StringBuilder values = new StringBuilder();

        row.forEach((column, value) -> {
            if (columns.length() > 0) {
                columns.append(", ");
                values.append(", ");
            }
            columns.append("`").append(column).append("`");
            values.append(formatValueForSql(value));
        });

        return "INSERT INTO `" + table + "` (" + columns + ") VALUES (" + values + ")";
    }

    private String formatValueForSql(Object value) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return ((Boolean) value) ? "1" : "0";
        }
        if (value instanceof java.sql.Date || value instanceof java.sql.Time || value instanceof Timestamp) {
            return "'" + value.toString() + "'";
        }
        String escaped = value.toString()
                .replace("\\", "\\\\")
                .replace("'", "''")
                .replace("\r", "\\r")
                .replace("\n", "\\n");
        return "'" + escaped + "'";
    }

    private String getDatabaseName() {
        try {
            // 首先检查连接池是否可用
            try {
                jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            } catch (Exception e) {
                System.err.println("⚠️  数据库连接不可用，使用默认数据库名");
                return "family_food_db";
            }
            
            return jdbcTemplate.queryForObject("SELECT DATABASE()", String.class);
        } catch (Exception e) {
            try {
                String url = jdbcTemplate.getDataSource().getConnection().getMetaData().getURL();
                int start = url.lastIndexOf("/");
                int end = url.indexOf("?", start);
                if (end == -1) {
                    end = url.length();
                }
                if (start != -1 && start + 1 < end) {
                    return url.substring(start + 1, end);
                }
            } catch (SQLException ex) {
                System.err.println("获取数据库名失败: " + ex.getMessage());
            }
            return "family_food_db";
        }
    }

    private int getTotalRecords(Map<String, List<Map<String, Object>>> tablesData) {
        return tablesData.values().stream().mapToInt(List::size).sum();
    }
}